### ISSUE TITLE
Get 3 redeclaration errors: may not have default arguments [-fpermissive]

### ISSUE THREAD

**Issue by Fiiti** [ITEAD-Thierry/NextionX#3]
Thanks again for such interesting work!

Unfortunately I get an error from my compiler and my skills are not strong enough to understand, what is here happen.

The error output:
`include/NextionX.h:96:71: error: redeclaration of 'NexComp::NexComp(NexComm_t&, uint8_t, uint8_t)' may not have default arguments [-fpermissive]`
` NexComp::NexComp(NexComm_t &nexComm, uint8_t pageId, uint8_t objId = 0) : _nexComm(&nexComm)`
`.....................................................................^`
` `
`include/NextionX.h:147:64: error: redeclaration of 'void NexComm::begin(nexSerType&, uint32_t)' may not have default arguments [-fpermissive]`
` void NexComm::begin(nexSerType &nexSer, uint32_t nexBaud = 9600)`
`...........................................................^`
` `
`include/NextionX.h:157:67: error: redeclaration of 'void NexComm::addDebug(dbgSerType&, uint32_t)' may not have default arguments [-fpermissive]`
` void NexComm::addDebug(dbgSerType &dbgSer, uint32_t dbgBaud = 9600)`
`..............................................................^`

![2021-02-15 18_22_34-NextionX h - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/25975978/107978564-4ad66a00-6fbd-11eb-9e07-8d6108168b37.png)

I am using an esp32 Dev Board with platformIO all the time. The 0.5 Version was working very well.
I tried to remove those integers, but in this case much more errors appear :(

Any idea, what I can do here?
Of course I added the #include<Arduino.h> of the main file, wich i also named main.cpp

Regards Fii

**Comment by ITEAD-Thierry** [comment]
Hi, that is an interesting question since I can not reproduce the issue (even in platformIO) when compiling for Arduino or Teensy. Probably, the esp32 toolchain uses a different C/C++ version, not C++11 like Arduino or C++14 like Teensy. I'll need some time to investigate since I haven't an ESP32 at hands for the moment. Please be patient, I'll for sure find a solution.
For the moment, you might proceed as follows:

- Change line 96 of NextionX.h from: 
_NexComp::NexComp(NexComm_t &nexComm, uint8_t pageId, uint8_t objId = 0) : _nexComm(&nexComm)_ 
to: 
_NexComp::NexComp(NexComm_t &nexComm, uint8_t pageId, uint8_t objId) : _nexComm(&nexComm)_

- Change line 147 of NextionX.h from: 
_void NexComm::begin(nexSerType &nexSer, uint32_t nexBaud = 9600)_
to:
_void NexComm::begin(nexSerType &nexSer, uint32_t nexBaud)_

- And finally, change line 157 of NextionX.h from:
_void NexComm::addDebug(dbgSerType &dbgSer, uint32_t dbgBaud = 9600)_
to:
_void NexComm::addDebug(dbgSerType &dbgSer, uint32_t dbgBaud)_

This should fix the compile error inside the library. But, afterwards, you'll need to specify the baud rates explicitly in the .begin() and .addDebug() methods of the NexComm object in your main.cpp file, like, for example, as follows:
_void setup() {
  myNex.begin(Serial1, **9600**);
  // Comment the next line out to disable debugging and to free up memory:
  myNex.addDebug(Serial, **9600**);_

**Comment by ITEAD-Thierry** [comment]
@Fiiti : could you please check out if the workaround above does work for you?

**Comment by Fiiti** [comment]
Okay, it seems that 2 errors are gone.
in main.cpp I added the baud:

void setup() {
  myNex.begin(Serial2, 9600);
  // Comment the next line out to disable debugging and to free up memory:
  myNex.addDebug(Serial, 9600);
  

__After compiling I have one Error:
  
  In file included from src\main.cpp:2:0:
include/NextionX.h:96:1: error: '_NexComp' does not name a type
 _NexComp::NexComp(NexComm_t &nexComm, uint8_t pageId, uint8_t objId) : nexComm(&nexComm)
 

![2021-02-15 22_06_21-NextionX h - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/25975978/107992965-21780700-6fda-11eb-841a-b1c59264ab90.png)

![2021-02-15 22_07_18-NextionX h - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/25975978/107992997-36549a80-6fda-11eb-8f88-daba948bcf41.png)
Translatet it means: "A name followed by "::" must be a class or namespace."

**Comment by ITEAD-Thierry** [comment]
Danke, ich verstehe auch etwas Deutsch… ;)

I’m sorry, but that was a copy and paste error here in GitHub. The underscore at the very first position is not part of the published original code. Take it away and you should be fine.

**Comment by Fiiti** [comment]
This error is also gone - but in the same line another failure appears:

include/NextionX.h: In constructor 'NexComp::NexComp(NexComm_t&, uint8_t, uint8_t)':
include/NextionX.h:96:71: error: class 'NexComp' does not have any field named 'nexComm'
 NexComp::NexComp(NexComm_t &nexComm, uint8_t pageId, uint8_t objId) : nexComm(&nexComm)
 
 I had the ambition to maybe solve this myself. But all these underscores, t's and colons create me.

**Comment by ITEAD-Thierry** [comment]
This time, it’s you having accidentally omitted the (needed!) underscore before NexComm(&nexComm) and after the colon, as I stated at the end of my previous message: 
NexComp::NexComp(NexComm_t &nexComm, uint8_t pageId, uint8_t objId) : _nexComm(&nexComm)

**Comment by Fiiti** [comment]
It works. But to my apology I must say, that I forget to write ist before.
If I add to the : _nexComm(&nexComm) 
PlatformIO shows me also an error:
![image](https://user-images.githubusercontent.com/25975978/108082256-30aa9380-7072-11eb-8baa-fdde6a78872b.png)

It just didn't occur to me that PlatformIO here was fibbing to me. 
Although the error is displayed, I have now pressed compile.

And what should I say: 
![image](https://user-images.githubusercontent.com/25975978/108082564-867f3b80-7072-11eb-8296-f0bfe58de64a.png)

And the error is gone.
Strange behavior.

To write these lines I could also recreate the problem. 

So many thanks, now I can start to flash and try and play and modify....

**Comment by ITEAD-Thierry** [comment]
Happy that it does now work for you and in your environment!
